In [2]:
import numpy as np

In [3]:
np.random.seed(0) # Siempre obtiene los mismos numeros aleatorios

x1 = np.random.randint(10,size=10)

x2 = np.random.randint(10,size=(3,3))

x3 = np.random.randint(10,size=(3,4,5))

In [4]:
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9 3 5 2 4]
[[7 6 8]
 [8 1 6]
 [7 7 8]]
[[[1 5 9 8 9]
  [4 3 0 3 5]
  [0 2 3 8 1]
  [3 3 3 7 0]]

 [[1 9 9 0 4]
  [7 3 2 7 2]
  [0 0 4 5 5]
  [6 8 4 1 4]]

 [[9 8 1 1 7]
  [9 9 3 6 7]
  [2 0 3 5 9]
  [4 4 6 4 4]]]


In [5]:
numeros = np.array([1,2,3,4,5])

# Indexación
numeros[1]

2

In [6]:
# Array Slicing
# x[start:stop:step]

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Obtiene los elementos desde la posición 0 hasta la 5
x[0:5]

array([0, 1, 2, 3, 4])

In [8]:
# Obtiene los primeros 5 elementos
x[:5]

array([0, 1, 2, 3, 4])

In [9]:
#Obtiene los elementos desde la posición 5
x[5:]

array([5, 6, 7, 8, 9])

In [10]:
#Obtiene los elementos de la posición 2 a la 7

x[2:7]

array([2, 3, 4, 5, 6])

In [11]:
#Obtiene los elementos de la posición 2 a la 7, de 2 en 2
x[2:7:2]

array([2, 4, 6])

In [12]:
# Revertir el arreglo

x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [13]:
pares = x[2:7:2][::-1]

pares

array([6, 4, 2])

In [14]:
x[7:2:-1]

array([7, 6, 5, 4, 3])

In [15]:
data = np.array([np.arange(i*5,i*5+5) for i in range(5)])

data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Slicing en arreglos multidimensionales

In [16]:
# x[row][column]
data[2][1]

11

In [17]:
data[2,1]

11

In [18]:
#Obtener las primeras dos filas y 3 columnas
data[ :2 , :3 ]

array([[0, 1, 2],
       [5, 6, 7]])

In [19]:
np.random.seed(0)
random_data= np.random.randint(10,size=(10,10))

random_data

array([[5, 0, 3, 3, 7, 9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1, 6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4, 3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3, 3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7, 3, 2, 7, 2, 0],
       [0, 4, 5, 5, 6, 8, 4, 1, 4, 9],
       [8, 1, 1, 7, 9, 9, 3, 6, 7, 2],
       [0, 3, 5, 9, 4, 4, 6, 4, 4, 3],
       [4, 4, 8, 4, 3, 7, 5, 5, 0, 1],
       [5, 9, 3, 0, 5, 0, 1, 2, 4, 2]])

In [20]:
# Obtener los elementos de las filas 4-7 y columnas 2-8

# Obtener los elementos de las filas 0-5 y columnas 0-3

# Obtener los elementos de as ultimas 3 filas y ultimas 5 columnas

In [21]:
random_data[4:7,2:8]

array([[0, 4, 7, 3, 2, 7],
       [5, 5, 6, 8, 4, 1],
       [1, 7, 9, 9, 3, 6]])

In [22]:
random_data[:5,:3]

array([[5, 0, 3],
       [7, 6, 8],
       [5, 9, 8],
       [2, 3, 8],
       [9, 9, 0]])

In [29]:
no_copy = random_data[-3:,-5:]
no_copy[0] = 50

no_copy

array([[50, 50, 50, 50, 50],
       [ 7,  5,  5,  0,  1],
       [ 0,  1,  2,  4,  2]])

In [31]:
copiaData = random_data[-3:,-5:].copy()

copiaData[1] = 100

In [32]:
copiaData

array([[ 50,  50,  50,  50,  50],
       [100, 100, 100, 100, 100],
       [  0,   1,   2,   4,   2]])

In [33]:
random_data

array([[ 5,  0,  3,  3,  7,  9,  3,  5,  2,  4],
       [ 7,  6,  8,  8,  1,  6,  7,  7,  8,  1],
       [ 5,  9,  8,  9,  4,  3,  0,  3,  5,  0],
       [ 2,  3,  8,  1,  3,  3,  3,  7,  0,  1],
       [ 9,  9,  0,  4,  7,  3,  2,  7,  2,  0],
       [ 0,  4,  5,  5,  6,  8,  4,  1,  4,  9],
       [ 8,  1,  1,  7,  9,  9,  3,  6,  7,  2],
       [ 0,  3,  5,  9,  4, 50, 50, 50, 50, 50],
       [ 4,  4,  8,  4,  3,  7,  5,  5,  0,  1],
       [ 5,  9,  3,  0,  5,  0,  1,  2,  4,  2]])

In [35]:
x = np.array([1,2,3])
y = np.array([3,2,1])

np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [41]:
# Uniendo matrices
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[1,2,3],[4,5,6]])

np.concatenate([m1,m2],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [44]:
np.r_[m1,m2]

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [49]:
x = [1,2,3,10,11,12,20,21,22]

x1,x2,x3 = np.split(x,[3,6])

print(x1)
print(x2)
print(x3)

[1 2 3]
[10 11 12]
[20 21 22]


In [47]:
matriz = np.array(x).reshape((3,3))
matriz

array([[ 1,  2,  3],
       [10, 11, 12],
       [20, 21, 22]])

In [50]:
upper,lower = np.vsplit(matriz,[2])

print(upper)
print(lower)

[[ 1  2  3]
 [10 11 12]]
[[20 21 22]]


# Universal functions

In [1]:
import numpy as np

np.random.seed(0)

values = np.random.randint(1,100,size=100)

print(values)

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89 82 38 26 78
 73 10 21 81 70 80 48 65 83 89 50 30 20 20 15 40 33 66 10 58 33 32 75 24
 36 76 56 29 35  1  1 37 54  6 39 18 80  5 43 59 32  2 66 42 58 36 12 47
 83 92  1 15 54 13 43 85 76 69  7 69 48  4 77 53 79 16 21 59 24 80 14 86
 49 50 70 42]


In [3]:
def reduce_10_percent(data):
    result = []
    for number in data:
        reduced = number * 0.9
        result.append(reduced)

    return result

In [5]:
%timeit reduce_10_percent(values)

104 µs ± 750 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [6]:
result = values*0.9

result

array([40.5, 43.2, 58.5, 61.2, 61.2,  9. , 75.6, 19.8, 33.3, 79.2, 63.9,
       80.1, 80.1, 11.7, 53.1, 59.4, 36. , 79.2, 42.3, 80.1, 73.8, 34.2,
       23.4, 70.2, 65.7,  9. , 18.9, 72.9, 63. , 72. , 43.2, 58.5, 74.7,
       80.1, 45. , 27. , 18. , 18. , 13.5, 36. , 29.7, 59.4,  9. , 52.2,
       29.7, 28.8, 67.5, 21.6, 32.4, 68.4, 50.4, 26.1, 31.5,  0.9,  0.9,
       33.3, 48.6,  5.4, 35.1, 16.2, 72. ,  4.5, 38.7, 53.1, 28.8,  1.8,
       59.4, 37.8, 52.2, 32.4, 10.8, 42.3, 74.7, 82.8,  0.9, 13.5, 48.6,
       11.7, 38.7, 76.5, 68.4, 62.1,  6.3, 62.1, 43.2,  3.6, 69.3, 47.7,
       71.1, 14.4, 18.9, 53.1, 21.6, 72. , 12.6, 77.4, 44.1, 45. , 63. ,
       37.8])

In [7]:
%timeit (values*0.9)

588 ns ± 3.37 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [8]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [10]:
x+5

array([5, 6, 7, 8])

In [11]:
x-5

array([-5, -4, -3, -2])

In [12]:
x*2

array([0, 2, 4, 6])

In [13]:
x/2

array([0. , 0.5, 1. , 1.5])

In [14]:
-x

array([ 0, -1, -2, -3])

In [15]:
x**2

array([0, 1, 4, 9])

In [16]:
fx = x**2 + 5
fx

array([ 5,  6,  9, 14])

In [19]:
x = np.arange(10)
y = np.arange(9)

result = x[:9]*y

result

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])

In [20]:
np.absolute(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x = np.arange(10)
y = np.random.random(10)

print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[0.94957105 0.66252687 0.01357164 0.6228461  0.67365963 0.971945
 0.87819347 0.50962438 0.05571469 0.45115921]


In [23]:
x*y

array([0.        , 0.66252687, 0.02714327, 1.86853829, 2.69463852,
       4.85972501, 5.26916083, 3.56737064, 0.44571755, 4.06043293])

In [25]:
data = np.linspace(0,np.pi,10)
data

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

In [26]:
np.sin(data)

array([0.00000000e+00, 3.42020143e-01, 6.42787610e-01, 8.66025404e-01,
       9.84807753e-01, 9.84807753e-01, 8.66025404e-01, 6.42787610e-01,
       3.42020143e-01, 1.22464680e-16])

In [27]:
np.cos(data)

array([ 1.        ,  0.93969262,  0.76604444,  0.5       ,  0.17364818,
       -0.17364818, -0.5       , -0.76604444, -0.93969262, -1.        ])

In [28]:
np.tan(data)

array([ 0.00000000e+00,  3.63970234e-01,  8.39099631e-01,  1.73205081e+00,
        5.67128182e+00, -5.67128182e+00, -1.73205081e+00, -8.39099631e-01,
       -3.63970234e-01, -1.22464680e-16])

In [30]:
# np.arcsin(),np.arccos(),np.arctan()
# np.exp(), np.log(), np.log2(), np.log10()

In [31]:
# scipy

In [32]:
# min, max, sum

data = np.random.random(100)

data.sum()

48.665754440143175

In [33]:
data.min()

0.009356704856532616

In [34]:
data.max()

0.9840422413641464

In [38]:
a = np.arange(3)

b = np.arange(3).reshape((3,1))

a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [3]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])