In [1]:
import numpy as np

In [35]:
np.random.seed(0) # Siempre obtiene los mismos numeros aleatorios

x1 = np.random.randint(10,size=10)

x2 = np.random.randint(10,size=(3,3))

x3 = np.random.randint(10,size=(3,4,5))

In [21]:
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9 3 5 2 4]
[[7 6 8]
 [8 1 6]
 [7 7 8]]
[[[1 5 9 8 9]
  [4 3 0 3 5]
  [0 2 3 8 1]
  [3 3 3 7 0]]

 [[1 9 9 0 4]
  [7 3 2 7 2]
  [0 0 4 5 5]
  [6 8 4 1 4]]

 [[9 8 1 1 7]
  [9 9 3 6 7]
  [2 0 3 5 9]
  [4 4 6 4 4]]]


In [2]:
numeros = np.array([1,2,3,4,5])

# Indexación
numeros[1]

2

In [3]:
# Array Slicing
# x[start:stop:step]

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Obtiene los elementos desde la posición 0 hasta la 5
x[0:5]

array([0, 1, 2, 3, 4])

In [5]:
# Obtiene los primeros 5 elementos
x[:5]

array([0, 1, 2, 3, 4])

In [6]:
#Obtiene los elementos desde la posición 5
x[5:]

array([5, 6, 7, 8, 9])

In [7]:
#Obtiene los elementos de la posición 2 a la 7

x[2:7]

array([2, 3, 4, 5, 6])

In [8]:
#Obtiene los elementos de la posición 2 a la 7, de 2 en 2
x[2:7:2]

array([2, 4, 6])

In [9]:
# Revertir el arreglo

x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [17]:
pares = x[2:7:2][::-1]

pares

array([6, 4, 2])

In [11]:
x[7:2:-1]

array([7, 6, 5, 4, 3])

In [20]:
data = np.array([np.arange(i*5,i*5+5) for i in range(5)])

data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Slicing en arreglos multidimensionales

In [22]:
# x[row][column]
data[2][1]

11

In [23]:
data[2,1]

11

In [27]:
#Obtener las primeras dos filas y 3 columnas
data[ :2 , :3 ]

array([[0, 1, 2],
       [5, 6, 7]])

In [40]:
np.random.seed(0)
random_data= np.random.randint(10,size=(10,10))

random_data

array([[5, 0, 3, 3, 7, 9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1, 6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4, 3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3, 3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7, 3, 2, 7, 2, 0],
       [0, 4, 5, 5, 6, 8, 4, 1, 4, 9],
       [8, 1, 1, 7, 9, 9, 3, 6, 7, 2],
       [0, 3, 5, 9, 4, 4, 6, 4, 4, 3],
       [4, 4, 8, 4, 3, 7, 5, 5, 0, 1],
       [5, 9, 3, 0, 5, 0, 1, 2, 4, 2]])

In [ ]:
# Obtener los elementos de las filas 4-7 y columnas 2-8

# Obtener los elementos de las filas 0-5 y columnas 0-3

# Obtener los elementos de as ultimas 3 filas y ultimas 5 columnas