In [2]:
import numpy as np

In [3]:
np.random.seed(0) # Siempre obtiene los mismos numeros aleatorios

x1 = np.random.randint(10,size=10)

x2 = np.random.randint(10,size=(3,3))

x3 = np.random.randint(10,size=(3,4,5))

In [4]:
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9 3 5 2 4]
[[7 6 8]
 [8 1 6]
 [7 7 8]]
[[[1 5 9 8 9]
  [4 3 0 3 5]
  [0 2 3 8 1]
  [3 3 3 7 0]]

 [[1 9 9 0 4]
  [7 3 2 7 2]
  [0 0 4 5 5]
  [6 8 4 1 4]]

 [[9 8 1 1 7]
  [9 9 3 6 7]
  [2 0 3 5 9]
  [4 4 6 4 4]]]


In [5]:
numeros = np.array([1,2,3,4,5])

# Indexación
numeros[1]

2

In [6]:
# Array Slicing
# x[start:stop:step]

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Obtiene los elementos desde la posición 0 hasta la 5
x[0:5]

array([0, 1, 2, 3, 4])

In [8]:
# Obtiene los primeros 5 elementos
x[:5]

array([0, 1, 2, 3, 4])

In [9]:
#Obtiene los elementos desde la posición 5
x[5:]

array([5, 6, 7, 8, 9])

In [10]:
#Obtiene los elementos de la posición 2 a la 7

x[2:7]

array([2, 3, 4, 5, 6])

In [11]:
#Obtiene los elementos de la posición 2 a la 7, de 2 en 2
x[2:7:2]

array([2, 4, 6])

In [12]:
# Revertir el arreglo

x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [13]:
pares = x[2:7:2][::-1]

pares

array([6, 4, 2])

In [14]:
x[7:2:-1]

array([7, 6, 5, 4, 3])

In [15]:
data = np.array([np.arange(i*5,i*5+5) for i in range(5)])

data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Slicing en arreglos multidimensionales

In [16]:
# x[row][column]
data[2][1]

11

In [17]:
data[2,1]

11

In [18]:
#Obtener las primeras dos filas y 3 columnas
data[ :2 , :3 ]

array([[0, 1, 2],
       [5, 6, 7]])

In [19]:
np.random.seed(0)
random_data= np.random.randint(10,size=(10,10))

random_data

array([[5, 0, 3, 3, 7, 9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1, 6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4, 3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3, 3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7, 3, 2, 7, 2, 0],
       [0, 4, 5, 5, 6, 8, 4, 1, 4, 9],
       [8, 1, 1, 7, 9, 9, 3, 6, 7, 2],
       [0, 3, 5, 9, 4, 4, 6, 4, 4, 3],
       [4, 4, 8, 4, 3, 7, 5, 5, 0, 1],
       [5, 9, 3, 0, 5, 0, 1, 2, 4, 2]])

In [20]:
# Obtener los elementos de las filas 4-7 y columnas 2-8

# Obtener los elementos de las filas 0-5 y columnas 0-3

# Obtener los elementos de as ultimas 3 filas y ultimas 5 columnas

In [21]:
random_data[4:7,2:8]

array([[0, 4, 7, 3, 2, 7],
       [5, 5, 6, 8, 4, 1],
       [1, 7, 9, 9, 3, 6]])

In [22]:
random_data[:5,:3]

array([[5, 0, 3],
       [7, 6, 8],
       [5, 9, 8],
       [2, 3, 8],
       [9, 9, 0]])

In [29]:
no_copy = random_data[-3:,-5:]
no_copy[0] = 50

no_copy

array([[50, 50, 50, 50, 50],
       [ 7,  5,  5,  0,  1],
       [ 0,  1,  2,  4,  2]])

In [31]:
copiaData = random_data[-3:,-5:].copy()

copiaData[1] = 100

In [32]:
copiaData

array([[ 50,  50,  50,  50,  50],
       [100, 100, 100, 100, 100],
       [  0,   1,   2,   4,   2]])

In [33]:
random_data

array([[ 5,  0,  3,  3,  7,  9,  3,  5,  2,  4],
       [ 7,  6,  8,  8,  1,  6,  7,  7,  8,  1],
       [ 5,  9,  8,  9,  4,  3,  0,  3,  5,  0],
       [ 2,  3,  8,  1,  3,  3,  3,  7,  0,  1],
       [ 9,  9,  0,  4,  7,  3,  2,  7,  2,  0],
       [ 0,  4,  5,  5,  6,  8,  4,  1,  4,  9],
       [ 8,  1,  1,  7,  9,  9,  3,  6,  7,  2],
       [ 0,  3,  5,  9,  4, 50, 50, 50, 50, 50],
       [ 4,  4,  8,  4,  3,  7,  5,  5,  0,  1],
       [ 5,  9,  3,  0,  5,  0,  1,  2,  4,  2]])

In [35]:
x = np.array([1,2,3])
y = np.array([3,2,1])

np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [41]:
# Uniendo matrices
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[1,2,3],[4,5,6]])

np.concatenate([m1,m2],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [44]:
np.c_[m1,m2]

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [49]:
x = [1,2,3,10,11,12,20,21,22]

x1,x2,x3 = np.split(x,[3,6])

print(x1)
print(x2)
print(x3)

[1 2 3]
[10 11 12]
[20 21 22]


In [47]:
matriz = np.array(x).reshape((3,3))
matriz

array([[ 1,  2,  3],
       [10, 11, 12],
       [20, 21, 22]])

In [50]:
upper,lower = np.vsplit(matriz,[2])

print(upper)
print(lower)

[[ 1  2  3]
 [10 11 12]]
[[20 21 22]]
